### PR TITLE
COD-848: Ensure case of metadata is correct when generated by policy …

### PR DESCRIPTION
**Pull request by ellielacework**
…create
### JIRA
https://lacework.atlassian.net/browse/COD-848

### Description
We are using the `policy create` command to write opal policies so we must ensure generated metadata is the correct case and follows existing patterns of the metadata so we don't break the UI or any other things in the process.

- Updated input options with correct case.
- Updated regex for `category` custom input to enforce expected case.
- `CheckType` case is applied while creating the metadata.yaml as lowercase is required for this value everywhere else.

### Test
Updated existing tests with correct cases. All passing.

### CODE REVIEW

**Comment by ellielacework** [comment]
> This looks good but we don't have a unique ID for any of this policy. Maybe we should ask the user to enter or we should create on our own..`SID` is a mandatory field in many places.

SID is resolved by api-server for both lacework authored and custom policies

**Comment by hemanthgk10** [comment]
are you sure on that as Leanthony was saying it is missing when I was speaking with him on the slack? Can we get the confirmation on that as we saw that in the polices when we called the policies API the SIDs are missing for them.

**Comment by ellielacework** [comment]
> are you sure on that as Leanthony was saying it is missing when I was speaking with him on the slack? Can we get the confirmation on that as we saw that in the polices when we called the policies API the SIDs are missing for them.

yep - I am sure... just did an upload of a custom policy to confirm. 
- uploaded a policy with no id in the metadata.
- the cli created an ID and added it to the metadata before upload.
- I can see the sid in the UI:
image

**Review by hemanthgk10 — APPROVED** [review]
Taking the discussion on SID as separate issue and getting this merged.

**Pull request merged**
