### PR TITLE
More IaC inventory types

### PR DESCRIPTION
**Pull request by Eriner**
Adds searching for Dockerfiles and for directories with k8s manifests. Manifest paths returned via XCP are now relative to the project repo.

~~WIP. Includes minor refactor, and one bug that that I haven't resolved yet (whereby all counts are set to zero in the results).~~

### CODE REVIEW

**Comment by slshen** [comment]
This is getting complicated enough that it should include a test.

Just create a tarball and put it in pkg/tools/iacinventory/testdata and run it against that asserting that it finds the right things.  It can be a pretty minimal tarball.

**Comment by Eriner** [comment]
Tests should have (mostly) full coverage and should be fairly maintainable. Tests are generated from `go generate` which will allow easy maintenance in the future.

**Review by slshen — COMMENTED** [review]
This is going to prevent folks from building on windows.

I think it'd be better to just check in the tar file.

**Comment by Eriner** [comment]
Is that *really* a problem? ;) (I kid).

**Pull request merged**
